import { execFileSync } from "node:child_process";
import { getFryBinary, type FryPluginConfig } from "./src/config.js";
import { createBuildStartTool } from "./src/tools/build-start.js";
import { createBuildStatusTool } from "./src/tools/build-status.js";
import { createBuildRestartTool } from "./src/tools/build-restart.js";
import { createBuildLogsTool } from "./src/tools/build-logs.js";
import { createReadProgressTool } from "./src/tools/read-progress.js";
import { createConsciousnessStatsTool } from "./src/tools/consciousness.js";
import { BuildWatcher } from "./src/service/build-watcher.js";

import type { OpenClawPluginApi } from "openclaw/plugin-sdk/fry";

let buildWatcher: BuildWatcher | null = null;

export default {
	id: "fry",
	name: "Fry Build Orchestration",
	description:
		"Start, monitor, and interact with Fry builds through OpenClaw's conversational interface",

	register(api: OpenClawPluginApi) {
		const config = (api.pluginConfig ?? {}) as FryPluginConfig;
		const fryBinary = getFryBinary(config);

		// Register tools
		api.registerTool(createBuildStartTool(fryBinary), { optional: true });
		api.registerTool(createBuildStatusTool(fryBinary), { optional: true });
		api.registerTool(createBuildRestartTool(fryBinary), { optional: true });
		api.registerTool(createBuildLogsTool(), { optional: true });
		api.registerTool(createReadProgressTool(), { optional: true });
		api.registerTool(createConsciousnessStatsTool(fryBinary), {
			optional: true,
		});

		// Load Fry's system prompt (generated by Go, lives in Go)
		let frySystemPrompt = "";
		try {
			frySystemPrompt = execFileSync(fryBinary, ["agent", "prompt"], {
				encoding: "utf-8",
				timeout: 5_000,
			});
		} catch (err) {
			api.logger.warn(
				`Could not load Fry system prompt: ${err instanceof Error ? err.message : String(err)}. Agent will operate without Fry expertise.`,
			);
		}

		// Inject Fry knowledge into agent system prompt
		if (frySystemPrompt) {
			api.on("before_prompt_build", () => {
				return {
					prependSystemContext: frySystemPrompt,
				};
			});
		}

		// Register build watcher service
		api.registerService({
			id: "fry-build-watcher",

			async start(ctx) {
				buildWatcher = new BuildWatcher(config, (message) => {
					// Use the API's channel dispatch to send proactive notifications.
					// The exact channel depends on the user's OpenClaw configuration.
					// For now, log and rely on the agent's next tool call to surface updates.
					ctx.logger.info(`[fry] ${message}`);
				});
				ctx.logger.info("Fry build watcher ready");
			},

			async stop(ctx) {
				buildWatcher?.stopAll();
				buildWatcher = null;
				ctx.logger.info("Fry build watcher stopped");
			},
		});

		api.logger.info("Fry extension registered");
	},
};

/**
 * Called by build-start tool to start watching a new build.
 * Exported for use by tool implementations.
 */
export function startWatchingBuild(projectDir: string): void {
	buildWatcher?.startWatching(projectDir);
}

/**
 * Stop watching a build (on completion or manual stop).
 */
export function stopWatchingBuild(projectDir: string): void {
	buildWatcher?.stopWatching(projectDir);
}
